=== 1709Sept25Java/batch-source/Week3CodeChallenge/WebContent/WEB-INF/countries.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT countries(country)>
<!ELEMENT country (country-name, country-capital)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT country-capital (#PCDATA)>

=== 1709Sept25Java/batch-source/Week3CodeChallenge/WebContent/WEB-INF/countries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE countries SYSTEM "countries.dtd">
<countries>
	<country>
		<country-name>Vietnam</country-name>
		<country-capital>Hanoi</country-capital>
	</country>
	<country>
		<country-name>United States</country-name>
		<country-capital>Washingon D.C</country-capital>
	</country>
	<country>
		<country-name>China</country-name>
		<country-capital>Beijing</country-capital>
	</country>
	<country>
		<country-name>Japan</country-name>
		<country-capital>Tokyo</country-capital>
	</country>
	<country>
		<country-name>France</country-name>
		<country-capital>Paris</country-capital>
	</country>
</countries>
